variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection:
  imageRepository:
  containerRegistry:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:

  - task: AzureWebAppContainer@1 # Description what the task will execute
    inputs:
      azureSubscription: ''
      appName: ''
      containers: $(containerRegistry)/$(imageRepository):$(tag)
