variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: devops-azure-container-registry-connection
  imageRepository: devops-course-repository
  containerRegistry: devopscourseregistry
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:

  - task: AzureWebAppContainer@1 # Description what the task will execute
    inputs:
      azureSubscription: 'devops-appservice-resource-course'
      appName: 'devops-course-webapp-test-lars'
      containers: $(containerRegistry)/$(imageRepository):$(tag)
